# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_to_import_started(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TranslationRequest = apps.get_model('djangocms_translations', 'TranslationRequest')
    TranslationRequest.objects.using(db_alias).filter(state='ready_for_import').update(state='import_failed')


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_to_import_started),
        migrations.AlterField(
            model_name='translationrequest',
            name='state',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_quote', 'Pending quote from provider'),
                         ('pending_approval', 'Pending approval of quote'),
                         ('ready_for_submission', 'Pending submission to translation provider'),
                         ('in_translation', 'In translation'), ('import_started', 'Import started'),
                         ('import_failed', 'Import failed'), ('imported', 'Imported'), ('cancelled', 'Cancelled')],
                default='draft', max_length=100),
        ),
    ]
