# -*- coding: utf-8 -*-
# Generated by Django 1.10.9.dev20170906233227 on 2017-11-25 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import cms.models.fields

import djangocms_translations.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('djangocms_translations', '0002_auto_20171122_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
                ('placeholder', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_placeholders', slotname=djangocms_translations.models._get_placeholder_slot, to='cms.Placeholder')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_placeholders', to='djangocms_translations.TranslationRequest')),
            ],
            options={
                'ordering': ('position',),
                'default_permissions': '',
            },
        ),
        migrations.CreateModel(
            name='ArchivedPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('old_plugin_id', models.IntegerField()),
                ('cms_plugin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trans_archived_plugin', to='cms.CMSPlugin')),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_plugins', to='djangocms_translations.ArchivedPlaceholder')),
            ],
            options={
                'default_permissions': '',
            },
        ),
    ]
