# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 14:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cms.models.fields

import djangocms_translations.models


def forward_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TranslationRequest = apps.get_model('djangocms_translations', 'TranslationRequest')
    TranslationRequest.objects.using(db_alias).all().update(target_cms_page=models.F('source_cms_page'))


def backward_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TranslationRequest = apps.get_model('djangocms_translations', 'TranslationRequest')
    TranslationRequest.objects.using(db_alias).all().update(target_cms_page=None)


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0003_archivedplaceholder_archivedplugin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationrequest',
            old_name='cms_page',
            new_name='source_cms_page',
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='source_cms_page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_as_source', to='cms.Page'),
        ),

        migrations.AlterField(
            model_name='translationrequest',
            name='source_language',
            field=models.CharField(choices=settings.LANGUAGES, max_length=10),
        ),

        migrations.AlterField(
            model_name='translationrequest',
            name='target_language',
            field=models.CharField(choices=settings.LANGUAGES, max_length=10),
        ),

        # 1: create field as nullable
        migrations.AddField(
            model_name='translationrequest',
            name='target_cms_page',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_as_target', to='cms.Page'),
        ),

        # 2: populate field
        migrations.RunPython(forward_migration, backward_migration),

        # 3: update field to non-nullable
        migrations.AlterField(
            model_name='translationrequest',
            name='target_cms_page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_as_target', to='cms.Page'),
        ),
    ]
