# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-28 13:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0005_auto_20180208_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(choices=[('started', 'Import Started'), ('failed', 'Import Failed'), ('imported', 'Imported')], default='started', max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='djangocms_translations.TranslationRequest')),
            ],
        ),
    ]
