# -*- coding: utf-8 -*-
# Generated by Django 2.1.4 on 2018-12-20 09:02
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations

import cms.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0008_auto_20180524_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedplugin',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='translationrequestitem',
            name='source_cms_page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_as_source', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='translationrequestitem',
            name='target_cms_page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_as_target', to='cms.Page'),
        ),
    ]
