# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0008_auto_20180524_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationorder',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
