# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('djangocms_translations', '0008_auto_20180524_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='source_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_requests_as_source', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='target_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_requests_as_target', to='sites.Site'),
        ),
    ]
