# Generated by Django 3.2.19 on 2023-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0009_auto_20181220_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationquote',
            name='delivery_date_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
